import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import slugify from 'slugify';
import { getVaultRoot, getAllMemoryFiles } from './config.js';
import { logger } from './logger.js';
import type { MemoryFile, WriteMemoryData } from './types.js';

export function slugifyFilename(str: string): string {
  return slugify(str, { lower: true, strict: true });
}

export function titleToFilename(title: string): string {
  return slugifyFilename(title) + '.md';
}

export function normalizePath(p: string): string {
  let normalized = p.replace(/\\/g, '/');
  if (!normalized.endsWith('.md')) {
    normalized += '.md';
  }
  return normalized;
}

export function getAbsolutePath(relativePath: string): string {
  return path.join(getVaultRoot(), relativePath);
}

export function readMemoryFile(relativePath: string): MemoryFile | null {
  const fullPath = getAbsolutePath(relativePath);
  if (!fs.existsSync(fullPath)) {
    logger.debug('Memory file not found', { path: relativePath });
    return null;
  }

  const raw = fs.readFileSync(fullPath, 'utf-8');
  const parsed = matter(raw);

  return {
    path: normalizePath(relativePath),
    title: (parsed.data.title as string) || path.basename(relativePath, '.md'),
    summary: (parsed.data.summary as string) || '',
    tags: Array.isArray(parsed.data.tags) ? (parsed.data.tags as string[]) : [],
    created: (parsed.data.created as string) || new Date().toISOString(),
    modified: (parsed.data.modified as string) || new Date().toISOString(),
    content: parsed.content,
    raw,
  };
}

export function writeMemoryFile(
  relativePath: string,
  data: WriteMemoryData,
): MemoryFile {
  const now = new Date().toISOString();
  const normalized = normalizePath(relativePath);
  const fullPath = getAbsolutePath(normalized);

  const dir = path.dirname(fullPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    logger.debug('Created directory', { dir });
  }

  let created = now;
  let relatedSection = data.relatedSection || '';

  if (fs.existsSync(fullPath)) {
    const existing = readMemoryFile(normalized);
    if (existing) {
      created = existing.created;
      if (!relatedSection) {
        const relatedMatch = existing.raw.match(
          /## Related\s*\n(?:<!--[^>]*-->\s*\n)?([\s\S]*?)(?=\n## |\n---|$)/,
        );
        if (relatedMatch) {
          relatedSection = relatedMatch[1].trim();
        }
      }
    }
  }

  const frontmatter = [
    '---',
    `title: "${data.title.replace(/"/g, '\\"')}"`,
    `created: "${created}"`,
    `modified: "${now}"`,
    `tags: [${data.tags.map((t) => t.replace(/"/g, '\\"')).join(', ')}]`,
    `summary: "${data.summary.replace(/"/g, '\\"')}"`,
    '---',
  ].join('\n');

  let body = data.content.trim();

  const relatedSplit = body.split(/\n## Related\b/);
  if (relatedSplit.length > 1) {
    body = relatedSplit[0].trimEnd();
  }

  if (relatedSection) {
    body +=
      '\n\n## Related\n<!-- Auto-generated by memory tool. Do not edit manually. -->\n' +
      relatedSection;
  } else {
    body +=
      '\n\n## Related\n<!-- Auto-generated by memory tool. Do not edit manually. -->\n';
  }

  const fullContent = frontmatter + '\n\n' + body + '\n';
  fs.writeFileSync(fullPath, fullContent, 'utf-8');
  logger.info('Wrote memory file', { path: normalized, title: data.title });

  return {
    path: normalized,
    title: data.title,
    summary: data.summary,
    tags: data.tags,
    created,
    modified: now,
    content: body,
    raw: fullContent,
  };
}

export function addRelatedLink(
  relativePath: string,
  linkedPath: string,
  linkedTitle: string,
): void {
  const memory = readMemoryFile(relativePath);
  if (!memory) {
    logger.warn('Cannot add related link: memory not found', { path: relativePath });
    return;
  }

  const linkedFullPath = getAbsolutePath(normalizePath(linkedPath));
  if (!fs.existsSync(linkedFullPath)) {
    logger.warn('Cannot add related link: linked memory not found on disk', {
      from: relativePath,
      linkedPath,
    });
    return;
  }

  const linkLine = `- [[${linkedPath.replace(/\.md$/, '')}]]`;

  let updatedRaw = memory.raw;
  const relatedMatch = updatedRaw.match(
    /## Related\s*\n(?:<!--[^>]*-->\s*\n)?([\s\S]*?)(?=\n## |\n---|\n*$)/,
  );

  if (relatedMatch) {
    const existingLinks = relatedMatch[1].trim();
    if (existingLinks.includes(`[[${linkedPath.replace(/\.md$/, '')}]]`)) {
      logger.debug('Related link already exists', { path: relativePath, linkedPath });
      return;
    }

    const beforeRelated = updatedRaw.substring(0, relatedMatch.index!);
    const afterRelated = updatedRaw.substring(
      relatedMatch.index! + relatedMatch[0].length,
    );
    const newLinks = existingLinks
      ? existingLinks + '\n' + linkLine
      : linkLine;
    updatedRaw =
      beforeRelated +
      '## Related\n<!-- Auto-generated by memory tool. Do not edit manually. -->\n' +
      newLinks +
      afterRelated;
  } else {
    updatedRaw =
      updatedRaw.trimEnd() +
      '\n\n## Related\n<!-- Auto-generated by memory tool. Do not edit manually. -->\n' +
      linkLine +
      '\n';
  }

  const fullPath = getAbsolutePath(relativePath);
  fs.writeFileSync(fullPath, updatedRaw, 'utf-8');
  logger.info('Added related link', { from: relativePath, to: linkedTitle });
}

export function getWikiLinks(relativePath: string): string[] {
  const memory = readMemoryFile(relativePath);
  if (!memory) return [];

  const matches = memory.raw.matchAll(/\[\[([^\]]+)\]\]/g);
  return [...matches].map((m) => m[1]);
}

export function removeRelatedLink(fromPath: string, linkedPath: string): boolean {
  const memory = readMemoryFile(fromPath);
  if (!memory) return false;

  const normalized = normalizePath(linkedPath);
  const linkRef = normalized.replace(/\.md$/, '');
  const linkLine = `- [[${linkRef}]]`;

  if (!memory.raw.includes(linkLine)) return false;

  const updatedRaw = memory.raw
    .split('\n')
    .filter((line) => line.trim() !== linkLine)
    .join('\n');

  const fullPath = getAbsolutePath(fromPath);
  fs.writeFileSync(fullPath, updatedRaw, 'utf-8');
  logger.info('Removed related link', { from: fromPath, linked: linkRef });
  return true;
}

export function findReferencingFiles(targetPath: string): string[] {
  const allFiles = getAllMemoryFiles();
  const normalized = normalizePath(targetPath);
  const ref = normalized.replace(/\.md$/, '');
  const referencing: string[] = [];

  for (const file of allFiles) {
    if (normalizePath(file) === normalized) continue;
    const memory = readMemoryFile(file);
    if (!memory) continue;

    const linkLine = `- [[${ref}]]`;
    if (memory.raw.includes(linkLine)) {
      referencing.push(file);
      continue;
    }

    const bodyLinks = memory.content.matchAll(/\[\[([^\]]+)\]\]/g);
    for (const match of bodyLinks) {
      if (match[1] === ref) {
        referencing.push(file);
        break;
      }
    }
  }

  return referencing;
}

export function replaceAllReferences(
  oldPath: string,
  newPath: string,
): number {
  const allFiles = getAllMemoryFiles();
  const oldRef = normalizePath(oldPath).replace(/\.md$/, '');
  const newRef = normalizePath(newPath).replace(/\.md$/, '');
  let changed = 0;

  for (const file of allFiles) {
    const fullPath = getAbsolutePath(file);
    let raw = fs.readFileSync(fullPath, 'utf-8');

    if (!raw.includes(oldRef)) continue;

    const updated = raw.replaceAll(oldRef, newRef);
    if (updated !== raw) {
      fs.writeFileSync(fullPath, updated, 'utf-8');
      changed++;
      logger.info('Replaced references', { file, oldRef, newRef });
    }
  }

  return changed;
}

export function deleteMemoryFile(relativePath: string): boolean {
  const normalized = normalizePath(relativePath);
  const fullPath = getAbsolutePath(normalized);

  if (!fs.existsSync(fullPath)) return false;

  fs.unlinkSync(fullPath);
  logger.info('Deleted memory file', { path: normalized });

  const dir = path.dirname(fullPath);
  try {
    const entries = fs.readdirSync(dir);
    if (entries.length === 0) {
      fs.rmdirSync(dir);
      logger.debug('Removed empty directory', { dir });
    }
  } catch {
    // directory might not be empty or already gone
  }

  return true;
}
