import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import slugify from 'slugify';
import { getMemoryRoot } from './config.js';
import type { MemoryFile, WriteMemoryData } from './types.js';

export function slugifyFilename(str: string): string {
  return slugify(str, { lower: true, strict: true });
}

export function titleToFilename(title: string): string {
  return slugifyFilename(title) + '.md';
}

export function normalizePath(p: string): string {
  let normalized = p.replace(/\\/g, '/');
  if (!normalized.endsWith('.md')) {
    normalized += '.md';
  }
  return normalized;
}

export function getAbsolutePath(relativePath: string): string {
  return path.join(getMemoryRoot(), relativePath);
}

export function readMemoryFile(relativePath: string): MemoryFile | null {
  const fullPath = getAbsolutePath(relativePath);
  if (!fs.existsSync(fullPath)) return null;

  const raw = fs.readFileSync(fullPath, 'utf-8');
  const parsed = matter(raw);

  return {
    path: normalizePath(relativePath),
    title: (parsed.data.title as string) || path.basename(relativePath, '.md'),
    summary: (parsed.data.summary as string) || '',
    tags: Array.isArray(parsed.data.tags) ? (parsed.data.tags as string[]) : [],
    created: (parsed.data.created as string) || new Date().toISOString(),
    modified: (parsed.data.modified as string) || new Date().toISOString(),
    content: parsed.content,
    raw,
  };
}

export function writeMemoryFile(
  relativePath: string,
  data: WriteMemoryData,
): MemoryFile {
  const now = new Date().toISOString();
  const normalized = normalizePath(relativePath);
  const fullPath = getAbsolutePath(normalized);

  const dir = path.dirname(fullPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  let created = now;
  let relatedSection = data.relatedSection || '';

  if (fs.existsSync(fullPath)) {
    const existing = readMemoryFile(normalized);
    if (existing) {
      created = existing.created;
      if (!relatedSection) {
        const relatedMatch = existing.raw.match(
          /## Related\s*\n([\s\S]*?)(?=\n## |\n---|$)/,
        );
        if (relatedMatch) {
          relatedSection = relatedMatch[1].trim();
        }
      }
    }
  }

  const frontmatter = [
    '---',
    `title: "${data.title.replace(/"/g, '\\"')}"`,
    `created: "${created}"`,
    `modified: "${now}"`,
    `tags: [${data.tags.map((t) => t.replace(/"/g, '\\"')).join(', ')}]`,
    `summary: "${data.summary.replace(/"/g, '\\"')}"`,
    '---',
  ].join('\n');

  let body = data.content.trim();

  if (relatedSection) {
    body +=
      '\n\n## Related\n<!-- Auto-generated by memory tool. Do not edit manually. -->\n' +
      relatedSection;
  } else {
    body +=
      '\n\n## Related\n<!-- Auto-generated by memory tool. Do not edit manually. -->\n';
  }

  const fullContent = frontmatter + '\n\n' + body + '\n';
  fs.writeFileSync(fullPath, fullContent, 'utf-8');

  return {
    path: normalized,
    title: data.title,
    summary: data.summary,
    tags: data.tags,
    created,
    modified: now,
    content: body,
    raw: fullContent,
  };
}

export function addRelatedLink(
  relativePath: string,
  linkedPath: string,
  linkedTitle: string,
): void {
  const memory = readMemoryFile(relativePath);
  if (!memory) return;

  const linkLine = `- [[${linkedTitle}]]`;

  if (memory.raw.includes(`[[${linkedTitle}]]`)) return;

  let updatedRaw = memory.raw;
  const relatedMatch = updatedRaw.match(
    /## Related\s*\n(?:<!--[^>]*-->\s*\n)?([\s\S]*?)(?=\n## |\n---|\n*$)/,
  );

  if (relatedMatch) {
    const beforeRelated = updatedRaw.substring(0, relatedMatch.index!);
    const afterRelated = updatedRaw.substring(
      relatedMatch.index! + relatedMatch[0].length,
    );
    const existingLinks = relatedMatch[1].trim();
    const newLinks = existingLinks
      ? existingLinks + '\n' + linkLine
      : linkLine;
    updatedRaw =
      beforeRelated +
      '## Related\n<!-- Auto-generated by memory tool. Do not edit manually. -->\n' +
      newLinks +
      afterRelated;
  } else {
    updatedRaw =
      updatedRaw.trimEnd() +
      '\n\n## Related\n<!-- Auto-generated by memory tool. Do not edit manually. -->\n' +
      linkLine +
      '\n';
  }

  const fullPath = getAbsolutePath(relativePath);
  fs.writeFileSync(fullPath, updatedRaw, 'utf-8');
}

export function getWikiLinks(relativePath: string): string[] {
  const memory = readMemoryFile(relativePath);
  if (!memory) return [];

  const matches = memory.raw.matchAll(/\[\[([^\]]+)\]\]/g);
  return [...matches].map((m) => m[1]);
}
