/**
 * Memory file operations — reading/writing .md files, frontmatter parsing
 */
import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import slugify from 'slugify';
import { getMemoryRoot } from './config.js';

/**
 * Slugify a string for use as a filename
 * @param {string} str
 * @returns {string}
 */
export function slugifyFilename(str) {
  return slugify(str, { lower: true, strict: true });
}

/**
 * Derive filename from title
 * @param {string} title
 * @returns {string}
 */
export function titleToFilename(title) {
  return slugifyFilename(title) + '.md';
}

/**
 * Normalize a path to use forward slashes and ensure .md extension
 * @param {string} p
 * @returns {string}
 */
export function normalizePath(p) {
  let normalized = p.replace(/\\/g, '/');
  if (!normalized.endsWith('.md')) {
    normalized += '.md';
  }
  return normalized;
}

/**
 * Get the full absolute path for a memory file
 * @param {string} relativePath
 * @returns {string}
 */
export function getAbsolutePath(relativePath) {
  return path.join(getMemoryRoot(), relativePath);
}

/**
 * Read a memory file and parse it
 * @param {string} relativePath - Path relative to memory root
 * @returns {import('./types.js').MemoryFile | null}
 */
export function readMemoryFile(relativePath) {
  const fullPath = getAbsolutePath(relativePath);
  if (!fs.existsSync(fullPath)) return null;

  const raw = fs.readFileSync(fullPath, 'utf-8');
  const parsed = matter(raw);

  return {
    path: normalizePath(relativePath),
    title: parsed.data.title || path.basename(relativePath, '.md'),
    summary: parsed.data.summary || '',
    tags: Array.isArray(parsed.data.tags) ? parsed.data.tags : [],
    created: parsed.data.created || new Date().toISOString(),
    modified: parsed.data.modified || new Date().toISOString(),
    content: parsed.content,
    raw,
  };
}

/**
 * Write a memory file to disk
 * @param {string} relativePath - Path relative to memory root
 * @param {Object} data
 * @param {string} data.title
 * @param {string} data.summary
 * @param {string[]} data.tags
 * @param {string} data.content - Markdown content (without frontmatter)
 * @param {string} [data.relatedSection] - Content for ## Related section
 * @returns {import('./types.js').MemoryFile}
 */
export function writeMemoryFile(relativePath, data) {
  const now = new Date().toISOString();
  const normalized = normalizePath(relativePath);
  const fullPath = getAbsolutePath(normalized);

  // Ensure directory exists
  const dir = path.dirname(fullPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  // Check if file exists to preserve created date
  let created = now;
  let relatedSection = data.relatedSection || '';

  if (fs.existsSync(fullPath)) {
    const existing = readMemoryFile(normalized);
    if (existing) {
      created = existing.created;
      // Preserve existing related section if not provided
      if (!relatedSection) {
        const relatedMatch = existing.raw.match(/## Related\s*\n([\s\S]*?)(?=\n## |\n---|$)/);
        if (relatedMatch) {
          relatedSection = relatedMatch[1].trim();
        }
      }
    }
  }

  // Build frontmatter
  const frontmatter = [
    '---',
    `title: "${data.title.replace(/"/g, '\\"')}"`,
    `created: "${created}"`,
    `modified: "${now}"`,
    `tags: [${data.tags.map(t => t.replace(/"/g, '\\"')).join(', ')}]`,
    `summary: "${data.summary.replace(/"/g, '\\"')}"`,
    '---',
  ].join('\n');

  // Build file content
  let body = data.content.trim();

  // Add Related section if there are links
  if (relatedSection) {
    body += '\n\n## Related\n<!-- Auto-generated by memory tool. Do not edit manually. -->\n' + relatedSection;
  } else {
    body += '\n\n## Related\n<!-- Auto-generated by memory tool. Do not edit manually. -->\n';
  }

  const fullContent = frontmatter + '\n\n' + body + '\n';
  fs.writeFileSync(fullPath, fullContent, 'utf-8');

  return {
    path: normalized,
    title: data.title,
    summary: data.summary,
    tags: data.tags,
    created,
    modified: now,
    content: body,
    raw: fullContent,
  };
}

/**
 * Add a wiki link to a memory's Related section
 * @param {string} relativePath - Memory file path
 * @param {string} linkedPath - Path to the linked memory
 * @param {string} linkedTitle - Title of the linked memory
 */
export function addRelatedLink(relativePath, linkedPath, linkedTitle) {
  const memory = readMemoryFile(relativePath);
  if (!memory) return;

  const linkLine = `- [[${linkedTitle}]]`;

  // Check if link already exists
  if (memory.raw.includes(`[[${linkedTitle}]]`)) return;

  // Find the Related section and append
  let updatedRaw = memory.raw;
  const relatedMatch = updatedRaw.match(
    /## Related\s*\n(?:<!--[^>]*-->\s*\n)?([\s\S]*?)(?=\n## |\n---|\n*$)/
  );

  if (relatedMatch) {
    const beforeRelated = updatedRaw.substring(0, relatedMatch.index);
    const afterRelated = updatedRaw.substring(
      relatedMatch.index + relatedMatch[0].length
    );
    const existingLinks = relatedMatch[1].trim();
    const newLinks = existingLinks
      ? existingLinks + '\n' + linkLine
      : linkLine;
    updatedRaw =
      beforeRelated +
      '## Related\n<!-- Auto-generated by memory tool. Do not edit manually. -->\n' +
      newLinks +
      afterRelated;
  } else {
    // No Related section yet, append one
    updatedRaw =
      updatedRaw.trimEnd() +
      '\n\n## Related\n<!-- Auto-generated by memory tool. Do not edit manually. -->\n' +
      linkLine +
      '\n';
  }

  const fullPath = getAbsolutePath(relativePath);
  fs.writeFileSync(fullPath, updatedRaw, 'utf-8');
}

/**
 * Get wiki links from a memory file
 * @param {string} relativePath
 * @returns {string[]}
 */
export function getWikiLinks(relativePath) {
  const memory = readMemoryFile(relativePath);
  if (!memory) return [];

  const matches = memory.raw.matchAll(/\[\[([^\]]+)\]\]/g);
  return [...matches].map(m => m[1]);
}
